name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore CancelCop.sln

    - name: Build
      run: dotnet build CancelCop.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test CancelCop.sln --configuration Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack src/CancelCop.Analyzer/CancelCop.Analyzer.csproj --configuration Release --no-build --output ./artifacts

    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
